services:
  - type: web
    name: kaugle-chat
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: daphne -b 0.0.0.0 -p 10000 omeglechat.asgi:application
    autoDeploy: true
